### ISSUE TITLE
Update advanced release to 11.00.02

### ISSUE THREAD

**Issue by sodface** [ceamac/netpbm-make-dist#1]
Hi @ceamac we are discussing changing the Alpine Linux package for netpbm from super stable to stable or advanced and I was planning on using your convenient repo releases as the source for the package.

Would you mind creating an 11.00.02 release for advanced?

See discussion here if interested:
https://gitlab.alpinelinux.org/alpine/aports/-/issues/14453

**Comment by ceamac** [comment]
Hi!

Starting with 11.0.2 I moved the releases to the gentoo dev space, here https://dev.gentoo.org/~ceamac/media-libs/netpbm/

But I will upload them here too if that is convenient

**Comment by ceamac** [comment]
Done

**Comment by sodface** [comment]
Oh great! I think the gentoo dev space will work fine too though I guess release notifications wouldn't be available. Whatever is easiest for you, it's my job to figure out how to maintain the Alpine package.
