### ISSUE TITLE
Release versioning should match upstream?

### ISSUE THREAD

**Issue by sodface** [ceamac/netpbm-make-dist#2]
This isn't a complaint because I appreciate being able to use this repo as source for the Alpine package, but for the new release I had the discussion pictured in the screenshot with the Alpine dev (Alice). [Link to Alpine MR.](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/42603)

Submitting for your consideration / comment.

![image](https://user-images.githubusercontent.com/46695384/209438020-c8603950-eb87-4534-97c2-4c32770f0306.png)

**Comment by ceamac** [comment]
I don't have strong opinions about this, but I cannot change the numbering now because of the way Gentoo versioning works.  11.0.3 > 11.00.04, so next upgrade would become a downgrade.

**Comment by ceamac** [comment]
I just checked, many netpbm executables actually report 11.0.3, not 11.00.03.  The version comes from a file named `version.mk`
```
$ pnmtops --version
pnmtops: Using libnetpbm from Netpbm Version: Netpbm 11.0.3
...
$ cat version.mk 
NETPBM_MAJOR_RELEASE = 11
NETPBM_MINOR_RELEASE = 0
NETPBM_POINT_RELEASE = 3
```

**Comment by sodface** [comment]
Hmmm, yes, I sort of blindly went with the numbering in the [change history](https://sourceforge.net/p/netpbm/code/HEAD/tree/advanced/doc/HISTORY) but now I think you made the right call to match what the executables report. I might have the opposite issue now with being able to change the Alpine package to 11.0.3, since 11.00.02 was already merged.

This was the comment that made me think going with 11.00.02 (now .03) was correct for the package I worked on. Oh well, sort of annoying, I'll see what Alpine wants to do.

> 22.09.28 BJH  Release 11.00.00
>
>             (No significance to new major number; just ran out of 2-digit
>              minor numbers).
>
>..snip..
>
> 22.06.24 BJH  Release 10.99.00

**Comment by sodface** [comment]
Alpine package changed to 11.0.3 version number. Thanks!
