### ISSUE TITLE
README update needed? 

### ISSUE THREAD

**Issue by sodface** [ceamac/netpbm-make-dist#3]
https://github.com/ceamac/netpbm-make-dist/blob/e6033523e660924a64bd1cf21cdeb4b052f6e929/README.md?plain=1#L1

Should this say advanced vs. stable? Or note that make-dist supports stable and advanced and that the releases are advanced? Maybe I'm confused.

**Comment by ceamac** [comment]
I added the `-a` option to build the advanced tarball, so I can build both.  They are both included in Gentoo.

From time to time, upstream moves stable to super stable, advanced to stable and dev to advanced, and the version numbers change suddenly.  Currently, the stable branch is at **11.2.x** and the advanced branch is at **11.3.x**.

You can read more about it [here](https://netpbm.sourceforge.net/release.html)

**Comment by ceamac** [comment]
I updated the README.

**Comment by sodface** [comment]
Right, I was familiar with the upstream release strategy but the README (prior to your update) would imply that the release tarballs were the stable version when the latest one is actually for advanced. You'd have to go upstream to figure it out based on the version number? I thought you previously had stable and advanced tarballs but maybe I'm mis-remembering.

**Comment by ceamac** [comment]
Yes, I put here both stable and advanced releases, but I don't have a naming schema for them.  I'll add this to the release notes next time.
